### ISSUE TITLE
Add audio file format validation

### ISSUE THREAD

**Issue by maximillianh** [EFForg/call-congress#19]
Twilio has repeatedly thrown 503 errors due to mismatch between the filetype of the recorded message and the extension, i.e. .mp4 or .wav files saved as .mp3.  We should either check the header or (ideally) use an audio library to load and attempt to play the file on upload.

**Comment by maximillianh** [comment]
This is unconfirmed, but we've had reports that the application is saving uploaded .wav files with the .mp3 extension.  This would cause Twilio to silently fail when attempting to play the audio file.

**Comment by vbrown608** [comment]
I'm seeing this issue (.wav saved as .mp3) locally.
